### PR TITLE
Wider gitignore file

### PR DESCRIPTION
**Pull request by Pimentoso**
Changed the gitignore to a template one, to catch all the files generated by virtualenv and many others generated by various IDEs.
Also for us people frequently pulling the master branch, I changed the config.ini to config.ini.sample (and the README accordingly) to not reset the config.ini changes each time.

### CODE REVIEW

**Comment by jgmcelwain** [comment]
+1 for .gitignore but there seem to be a few files in here that weren't part of PR description

**Comment by earshel** [comment]
I just committed another PR that had changes to the config file and readme. I would like to commit the gitignore file, though. I'm not very familiar with GitHub. If you can change the PR to just include the gitignore file, I'd happily commit it. Thanks for the help!

**Comment by Pimentoso** [comment]
The main idea is that every file that has to be changed by the user, or gets changed at runtime by the program, should be added to the gitignore file, so people pulling your repo changes don't get a merge conflict everytime. I just noticed that there are more files that need changing
- snipe.py should not be edited by the user to specify the encrypt lib, it should be read from the config.ini
- static/catch_data.json should be added to gitignore
- static/inventory.json should be added to gitignore
- static/stats.json should be added to gitignore

I'll see if I can remove files from this PR (never done it)

**Comment by earshel** [comment]
Thank you for the explanation. If you're not able to remove files from the PR it's no problem - just submit a new one with the gitignore file and I will commit it.

**Comment by jgmcelwain** [comment]
@Pimentoso I fixed the first point in a previous pull request.

I believe you can remove the files from the pull request by deleting the files from your repo, pushing that commit and updating this pull request with that commit. You can then add the files back into your own repo.

**Comment by Pimentoso** [comment]
Synced my repo and resolved the conflict. Sorry for the dashboard file but looks like my editor changed the indentation.

**Pull request merged**
